#!/usr/bin/env ruby
# frozen_string_literal: true

# Always look in the lib directory of this gem
# first when searching the load path
$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "ombu_labs/shortener/cli/application"

MyCLI.start(ARGV)

